#
###################################
# Site wide configuration
####################################
#
title: Libo Su's Blog 
email: sulibozju@gmail.com
description: Welcome to my blog.
url: "https://sulibo.github.io" # the base hostname & protocol for your site
keywords: ["Time Delay System","Control Theory"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Plugins  
plugins: ['jekyll/scholar']

# Jekyll Scholar 
scholar: 
  style: apa
  source: ./_data/bibliography
  bibliography: references.bib
  bibliography_list_tag: ul 

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Libo Su
  avatar: avatar.jpg
  job: "PhD Candidate"
  bio: "A PhD Candidate at KU Leuven, Belgium"
  email: sulibozju@gmail.com
  disqus-shortname: libosu
  twitter: sulibozju #username
  facebook: #username
  google:
    plus: #116672468031938485533 #username
    analytics: UA-42887873-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sulibo #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sulibo #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: 1923994851 #username
  flickr: #username
  codepen: #username
  telegram: #username
